In [ ]:
# ^_^ 메인 코딩 - H 첫 행 0,0으로, zd에 gaussian noise 추가
import numpy as np  #numpy함수를 np로 부르겠다~
import random
from matplotlib import pyplot as plt

H= np.matrix([[10,10],[110,10],[10,110],[110,110]]) ##matrix함수는 ,하면 enter친 것 처럼 열?이 바뀐다. 옆으로 나열이 아님)
x= 100*random.random()# 임의의 곳에 우리가 측정해야할 MS를 놓는다.
y= 100*random.random()
mu=0
size=4 # H의 사이즈. multi함수 밖이기 때문에 Ha의 사이즈가 아니다.
# Hx=b ,zd는 r1,r2,r3,r4
def multi(H,zd) :
  H=H-H[0] # multi함수 내에서 Ha만들 때 H 첫 번째 항 0,0으로 만들기
  Ha=np.delete(H,(0), axis=0) # np.delete(H,(0),axis=0))  (0)은 첫번째 행 삭제, axis=0은  
  r=np.delete(zd,(0), axis=0) # r=[r2, r3, r4..]
  r=np.multiply(r,r)
  K=np.multiply(Ha,Ha)
  K=K.sum(axis=1)
  r1=zd[0]
  r1=np.multiply(r1,r1)
  r1=r1.sum(axis=1)
  b=0.5*(K-r+r1)
  x_hat=(Ha.T*Ha).I*Ha.T*b
  x_hat=np.transpose(x_hat)
  return x_hat


MAE=[0] # noise로 인한 오차를 1000번의 시행의 오차의 제곱을 다 더하고 제곱씌워 평균을 구함.
for i in range(1,30): #시그마를 0.1~3까지 0.1일 때 0.2일 때..를 본다.
  e_cnt=[0] #e-count, n번째 오차를 n행에 넣는다.
  for j in range(1,1000):
    sigma = i/10
    n=np.random.normal(mu,sigma,size) ## 0 is the mean of the normal distribution you are choosing from
                                    # 1 is the standard deviation of the normal distribution
                                    # 100 is the number of elements you get in array noise
    xm=[50,50]
    zd=xm-H # [[xm-x1,ym-y1], [xm-x2, ym-y2]...
    zd=np.multiply(zd,zd) # 차이제곱
    zd=zd.sum(axis=1) # x2+y2
    zd=np.sqrt(zd) # 비로소 r1 r2 r3
    zd=zd + n.reshape(4,1)
    print(zd[0])
    x_hat=multi(H,zd)   #multi 함수 통해 도출한 태그의 좌표 출력
    #print(x_hat)
    e=xm-x_hat
    e=np.multiply(e,e)
    e=e.sum(axis=1)     #Mean Square Root(MSR) 계산
    e=np.sqrt(e)
    e_cnt.append(e)
    #print(e)
  MAE_tmp=sum(e_cnt)/1000
  MAE.append(MAE_tmp)
print(MAE)
plt.plot(range(0,30),MAE)
plt.xlabel('10*Standard Deviation [m]')
plt.ylabel('MAE [m]')
plt.show()
max_MAE=max(MAE)
print(max_MAE)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[[56.73887686]]
[[55.99028156]]
[[52.82548499]]
[[56.48301542]]
[[58.64648165]]
[[57.28843791]]
[[58.76582026]]
[[57.19190393]]
[[59.02442842]]
[[56.1975375]]
[[54.33277936]]
[[57.01759179]]
[[58.01117083]]
[[54.58262914]]
[[58.29574001]]
[[54.73250902]]
[[56.14951706]]
[[54.52576225]]
[[54.92009776]]
[[57.53150965]]
[[55.91528209]]
[[57.07106948]]
[[57.84791501]]
[[53.41400862]]
[[54.34816568]]
[[61.56651502]]
[[56.32860614]]
[[52.9818989]]
[[54.88803552]]
[[53.75512426]]
[[57.75116732]]
[[55.828016]]
[[58.55960339]]
[[59.00159969]]
[[53.31775375]]
[[57.49991432]]
[[53.96583493]]
[[58.60347591]]
[[55.04148331]]
[[53.03793299]]
[[54.65634444]]
[[57.86134367]]
[[55.48431061]]
[[56.39834558]]
[[52.80151258]]
[[57.77628712]]
[[54.45708161]]
[[59.24285439]]
[[52.81813945]]
[[56.92162086]]
[[56.13029624]]
[[54.09285457]]
[[53.943384]]
[[56.28231248]]
[[59.00997759]]
[[56.20124882]]
[[58.47279063]]
[[56.75599732]]
[[61.87726904]]
[[54.61538037]]
[[55.33762

KeyboardInterrupt: ignored

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
xm=[50,50]
zd=xm-H # [[xm-x1,ym-y1], [xm-x2, ym-y2]...
zd=np.multiply(zd,zd) # 차이제곱
zd=zd.sum(axis=1) # x2+y2
zd=np.sqrt(zd) # 비로소 r1 r2 r3
n=np.random.normal(mu,sigma,size)
mu=0
sigma=1
size=4

print(n)
print(zd)

[-0.52531895 -2.36705318 -5.01680179  1.42921398]
[[56.56854249]
 [72.11102551]
 [72.11102551]
 [84.85281374]]


In [ ]:

import numpy as np  #numpy함수를 np로 부르겠다~
import random

mu=0
sigma=1
size=4 # H의 사이즈. multi함수 밖이기 때문에 Ha의 사이즈가 아니다.

H= np.matrix([[1,2],[100,0],[0,100],[100,100]]) ##matrix함수는 ,하면 enter친 것 처럼 열?이 바뀐다. 옆으로 나열이 아님)
H=H-H[0]
x= 100*random.random()# 임의의 곳에 우리가 측정해야할 MS를 놓는다.
y= 100*random.random()

xm=[x,y]        #태그의 좌표
zd=xm-H # [[xm-x1,ym-y1], [xm-x2, ym-y2]...
zd=np.multiply(zd,zd) # 차이제곱
zd=zd.sum(axis=1) # x2+y2
zd=np.sqrt(zd) # 비로소 r1 r2 r3
n=np.random.normal(mu,sigma,size)

print(n)

[-0.6871508   0.92219122 -1.59356959 -0.63055615]


In [ ]:
import numpy as np  #numpy함수를 np로 부르겠다~
import random

H= np.matrix([[1,2],[100,0],[0,100],[100,100]])
H=H-H[0]
print(H)

[[ 0  0]
 [99 -2]
 [-1 98]
 [99 98]]
